# MkDocs Deployment Configuration
pages:
    image: python:3.9-slim
    before_script:
        - apt-get update && apt-get install -y git
        - pip install -r requirements.txt
        - git clone https://uva-hva.gitlab.host/hbo-ict/mdocotion.git mdocotion
        - cd mdocotion && python setup.py install && cd ..
    stage: deploy
    when: always
    tags:
        - hva
    script:
        - mkdocs build --site-dir public
    artifacts:
        paths:
            - public
