version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sm3test
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "db" ]
      interval: 10s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./src/election-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sm3test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:  # Empty password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    command: [ "sh", "-c", "until nc -z db 3306; do sleep 1; done; java -jar app.jar" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./src/election-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173" # port mapping
    volumes:
      - ./src/election-frontend:/app   # Mount the frontend code for hot reload
      - /app/node_modules
      - ./src/election-frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      NODE_ENV: development
    depends_on:
      - backend
    restart: always

volumes:
  db_data: