version: '3.8'  # Add version to the top

services:
  backend:
    build:
      context: ./src/election-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sm3test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  frontend:
    build:
      context: ./src/election-frontend
    ports:
      - "80:80"
      
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: sm3test
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
