services:
  backend:
    build:
      context: ./src/election-backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/zkaradue2
      SPRING_DATASOURCE_USERNAME: karadue2
      SPRING_DATASOURCE_PASSWORD: UJ5LSMo+z7.Qp2
    depends_on:
      - database
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./src/election-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: zkaradue2
      MYSQL_USER: karadue2
      MYSQL_PASSWORD: UJ5LSMo+z7.Qp2
    ports:
      - "3306:3306"
